version: "3.8"

services:
  app:
    container_name: goat_app
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    environment:
      - ENV=local

  db:
    container_name: goat_db
    image: postgres:16.1
    environment:
      POSTGRES_DB: goat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data 