services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    command: sh -c "go mod tidy && go build cmd/goat/main.go && ./main"
    restart: always