CREATE TABLE IF NOT EXISTS USERS (
	UID INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(100) NOT NULL,
	CREATE_AT TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime')),
	UPDATE_AT TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime'))
);

CREATE TRIGGER IF NOT EXISTS trigger_users_updated_at AFTER UPDATE ON USERS
BEGIN
    UPDATE USERS 
    	SET UPDATE_AT = DATETIME('now', 'localtime') 
    	WHERE rowid == NEW.rowid;
END;