CREATE TABLE IF NOT EXISTS USERS (
	USER_ID SERIAL PRIMARY KEY,
	USER_NAME TEXT NOT NULL UNIQUE,
	PASSWORD TEXT NOT NULL,
	CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

create trigger users_update_trg before update on users for each row
  	execute procedure set_update_time();