USE goat;

CREATE TABLE IF NOT EXISTS account (
	account_id INT AUTO_INCREMENT PRIMARY KEY,
	account_name VARCHAR(255) NOT NULL UNIQUE,
	account_password TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);