CREATE TABLE IF NOT EXISTS USERS (
	USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_NAME TEXT NOT NULL UNIQUE,
	PASSWORD TEXT NOT NULL,
	CREATE_AT TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime')),
	UPDATE_AT TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime'))
);

CREATE TRIGGER IF NOT EXISTS trigger_users_updated_at AFTER UPDATE ON USERS
BEGIN
    UPDATE USERS 
    	SET UPDATE_AT = DATETIME('now', 'localtime') 
    	WHERE rowid == NEW.rowid;
END;